/*
 * This source file was generated by the Gradle 'init' task
 */
package com.raggesilver.tp2;

public class App {
  public static void main(String[] args) {
    System.out.println(new App().getGreeting());
  }

  public String getGreeting() {
    return "Hello World!";
  }
}
