name: Programming Club CI

on:
  workflow_dispatch: {}
  push:
    paths:
      - ".github/workflows/programming_club.yml"
      - "programming_club/**/*.c"
      - "programming_club/algorithms/**/meson.build"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: ["programming_club/algorithms/24.2T", "programming_club/algorithms/24.3T"]
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4
      - id: setup-gcc
        name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64
      # TODO: use https://github.com/marketplace/actions/changed-files to
      # only check changed files
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: python -m pip install meson ninja
      - id: test
        name: Run test
        working-directory: ${{ matrix.dir }}
        run: |
          meson setup build
          meson compile -C build
          meson test -C build
